name: 📜 Documentation Inconsistency 📜
description: Please report any inconsistencies found in any of the Google Docs OR if something in Emerald Imperium is different than the data found on ([the Radical Red dex](https://dex.radicalred.net/)) and it is NOT explicitly mentioned.
Examples include;
- Bulbasaur is supposed to leanr Growl at level 3 according to RRDex, but your Bulbasaur didn't learn Growl at level 3! Please report that here.
- The Google Doc says that you can find Poochyena on Route 101, but you notice Poochyena is actually unavailable on Route 101! Please report that here.
labels: ["doc-inconsistency"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill in all required fields with as many details as possible.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe the issue you are experiencing.
        Attach images/videos if possible.
      placeholder: |
        Please enter a description of the issue. Here you can also attach log screenshots, gifs or a video
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Discord contact info
      description: Provide your Discord tag here so we can contact you in case we need more details. Be sure to join the Discord server ([here](https://discord.gg/XJkctHqR)).
      placeholder: ex. iriv24#8479
    validations:
      required: false
