blank_issues_enabled: false
contact_links:
  - name: Emerald Imperium's Discord server!
    url: https://discord.gg/AgJReMpxr6
    about: You can follow the development of Emerald Imperium and hang out with other folks who enjoy the game there!
